export const moodToKeyword = {
  happy: "feel good hits, upbeat pop, dance pop, summer vibes",
  sad: "sad songs, emotional ballads, melancholic indie, rainy day",
  energetic:
    "workout motivation, high-energy rock, electronic dance, pump-up anthems",
  chill: "lofi beats, chill vibes, acoustic chill, easy listening",
  romantic: "love songs, slow jams, acoustic love, R&B love ballads",
  nostalgic: "80s classics, throwback hits, 90s pop, early 2000s vibes",
  party: "party anthems, club hits, dance music, festival bangers",
  calm: "soft piano, instrumental ambient, deep relaxation, meditation music",
  focus: "deep focus, study beats, classical study, concentration music",
  angry: "hard rock, heavy metal, aggressive rap, punk energy",
  dreamy: "synthwave, cinematic ambient, ethereal sounds, dream pop",
  adventurous: "epic orchestral, cinematic scores, adventure soundtrack",
  roadtrip: "indie road trip, classic rock, folk travel, feel-good travel",
  night: "late-night vibes, deep house, jazz lounge, slow R&B",
  morning: "morning acoustic, wake-up pop, fresh start, uplifting indie",
  workout:
    "high-intensity EDM, gym motivation, running music, powerlifting beats",
  chillwave: "indie chillwave, synthwave chill, vaporwave, dreamy beats",
  meditative:
    "binaural beats, deep meditation, spiritual ambient, mindfulness music",
  horror: "dark ambient, eerie orchestral, horror synth, suspense soundtrack",
  study: "instrumental study, lo-fi study beats, soft classical, white noise",
  sleepy: "sleep sounds, ASMR rain, piano lullabies, gentle ambient",
  road_rage: "metalcore, hard rock, aggressive hip-hop, intense beats",
  summer: "sunny pop, tropical house, beach vibes, reggae chill",
  winter: "cozy acoustic, jazz holiday, warm piano, slow folk",
};

export const emojiMap = {
  happy: "😊",
  sad: "😢",
  energetic: "⚡",
  chill: "😌",
  romantic: "❤️",
  nostalgic: "🎵",
  party: "🎉",
  calm: "🌿",
  focus: "🎧",
  angry: "🔥",
  dreamy: "🌙",
  adventurous: "🧭",
  roadtrip: "🚗",
  night: "🌌",
  morning: "🌅",
  workout: "🏋️",
  chillwave: "🌊",
  meditative: "🧘",
  horror: "👻",
  study: "📚",
  sleepy: "😴",
  road_rage: "🚨",
  summer: "🌞",
  winter: "❄️",
};
